ALTER TABLE briefs ADD COLUMN IF NOT EXISTS ugc_selected_persona_id INTEGER;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS ugc_script JSONB DEFAULT NULL;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS ugc_script_edited BOOLEAN DEFAULT false;
