ALTER TABLE briefs ADD COLUMN IF NOT EXISTS ai_voiceover_url TEXT DEFAULT NULL;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS ai_voiceover_voice_id TEXT DEFAULT NULL;
ALTER TABLE briefs ADD COLUMN IF NOT EXISTS ai_voiceover_generated_at TIMESTAMP DEFAULT NULL;
